### Core settings ###

active: true
ready: true
centralizedSecretName: ckan-infra
# debugMode: NO
ckanStorageClassName: cca-ckan
storageClassName: cca-storage
useCentralizedInfra: true
usePersistentVolumes: true
withSansSSL: true
useCloudStorage: false

### App versions ###

ckanHelmChartRepo: https://raw.githubusercontent.com/hasadna/ckan-cloud-helm/master/charts_repository
ckanHelmChartVersion: 0.0.0-a98a4e8aef3037c1c9bf18bb9794e94e0e87e667
ckanImage: "datacity/ckan:11a09699cb7864b0df09664e655874902717dddd"
ckanOperatorImage: "datacity/cca-operator:11a09699cb7864b0df09664e655874902717dddd"

### Infrastructure / Resources ###

ckanPodReplaceStrategy: Recreate
replicas: 1
nginxReplicas: 1
ckanGunicornWorkers: 2
ckanLivenessPeriodSeconds: 300
ckanResources: '{"requests": {"cpu": "0.2", "memory": "400Mi"}, "limits": {"memory": "2Gi"}}'
nginxResources: '{"requests": {"cpu": "0.05", "memory": "300Mi"}, "limits": {"memory": "800Mi"}}'
ckanJobsDbResources: '{"requests": {"cpu": "0.02", "memory": "50Mi"}, "limits": {"memory": "200Mi"}}'
ckanJobsResources: '{"requests": {"cpu": "0.1", "memory": "400Mi"}, "limits": {"memory": "1500Mi"}}'
redisResources: '{"requests": {"cpu": "0.05", "memory": "100Mi"}, "limits": {"memory": "300Mi"}}'
ckanJobsDbTerminationGracePeriodSeconds: 30
ckanJobsTerminationGracePeriodSeconds: 30
jobsDbPersistentDiskSizeGB: 5
terminationGracePeriodSeconds: 30

### Core CKAN settings ###

ckanPlugins: stats text_view image_view recline_view datastore xloader resource_proxy s3filestore geojson_view
ckanDefaultViews: image_view text_view recline_view geojson_view
displayTimezone: Asia/Jerusalem
favIcon: /base/images/ckan.ico
siteDescription: Hasadna Datacity Demo
siteLogo: /base/images/ckan-logo.png
siteTitle: Hasadna Datacity Demo
#siteUrl: https://ckan-cloud-a-ckan-instance.ckan-aws-testing.gq

operatorCopySecrets: '{"ckan-instance":{"fromName":"ckan-instance-__INSTANCE_NAME__"}}'

extraCkanContainerEnvs: |
  - name: S3_FILESTORE_AWS_HOST_NAME
    valueFrom: {"secretKeyRef": {"name": "ckan-instance", "key": "S3_FILESTORE_AWS_HOST_NAME"}}
  - name: S3_FILESTORE_AWS_ACCESS_KEY_ID
    valueFrom: {"secretKeyRef": {"name": "ckan-instance", "key": "S3_FILESTORE_AWS_ACCESS_KEY_ID"}}
  - name: S3_FILESTORE_AWS_SECRET_ACCESS_KEY
    valueFrom: {"secretKeyRef": {"name": "ckan-instance", "key": "S3_FILESTORE_AWS_SECRET_ACCESS_KEY"}}
  - name: S3_FILESTORE_AWS_BUCKET_NAME
    valueFrom: {"secretKeyRef": {"name": "ckan-instance", "key": "S3_FILESTORE_AWS_BUCKET_NAME"}}
  - name: S3_FILESTORE_AWS_REGION_NAME
    valueFrom: {"secretKeyRef": {"name": "ckan-instance", "key": "S3_FILESTORE_AWS_REGION_NAME"}}

extraCkanConfig: |
  ckan.locale_default = he
  ckan.locale_order = en pt_BR ja it cs_CZ ca es fr el sv sr sr@latin no sk fi ru de pl nl bg ko_KR hu sa sl lv
  ckan.locales_offered = he ar en
  ckan.locales_filtered_out = en_GB
  ckanext.s3filestore.host_name = {{S3_FILESTORE_AWS_HOST_NAME}}
  ckanext.s3filestore.aws_access_key_id = {{S3_FILESTORE_AWS_ACCESS_KEY_ID}}
  ckanext.s3filestore.aws_secret_access_key = {{S3_FILESTORE_AWS_SECRET_ACCESS_KEY}}
  ckanext.s3filestore.aws_bucket_name = {{S3_FILESTORE_AWS_BUCKET_NAME}}
  ckanext.s3filestore.region_name = {{S3_FILESTORE_AWS_REGION_NAME}}
  ckanext.s3filestore.signature_version = s3v4
  ckanext.s3filestore.check_access_on_startup = false
  ckanext.s3filestore.create_if_not_exists = false

### CKAN auth settings ###

authAnon_create_dataset: "false"
authCreate_dataset_if_not_in_organization: "true"
authCreate_unowned_dataset: "false"
authCreate_user_via_api: "false"
authCreate_user_via_web: "true"
authRoles_that_cascade_to_sub_groups: admin
authUser_create_groups: "false"
authUser_create_organizations: "false"
authUser_delete_groups: "false"
authUser_delete_organizations: "false"

#dataStoreDbPersistentDiskSizeGB: 20
#datastoreDbResources: '{"requests": {"cpu": "100m", "memory": "200Mi"}, "limits": {"memory": "600Mi"}}'
#datastoreDbTerminationGracePeriodSeconds: 30
#dbPersistentDiskSizeGB: 20
#dbResources: '{"requests": {"cpu": "100m", "memory": "200Mi"}, "limits": {"memory": "600Mi"}}'
#dbTerminationGracePeriodSeconds: 30
#domain: ckan-cloud-a-ckan-instance.ckan-aws-testing.gq
#id: a-ckan-instance
#kind: datapusher
#name: a-ckan-instance
#provisioningKindTitle: DataPusher / Catalog
#registerSubdomain: ckan-cloud-a-ckan-instance
#solrPersistentDiskSizeGB: 10
#solrResources: '{"requests": {"cpu": "60m", "memory": "600Mi"}, "limits": {"memory": "1Gi"}}'
