apiVersion: v1
kind: ServiceAccount
metadata:
  name: dgp-operator-runner
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dgp-operator-runner
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "patch"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dgp-operator-runner
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: dgp-operator-runner
subjects:
- kind: ServiceAccount
  name: dgp-operator-runner
