apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: dgp-operator-runner
spec:
  entrypoint: dgp-operator-runner
  templates:
    - name: dgp-operator-runner
      serviceAccountName: dgp-operator-runner
      inputs:
        parameters:
          - name: operator
          - name: config_json
      container:
        image: ghcr.io/hasadna/hasadna-k8s/hasadna-k8s:4acd747fb77dfa1f9210c50ecae51bc89500bfad
        command: ["bash", "-c"]
        args:
          - |
            set -euo pipefail
            kubectl -n datacity exec -c server deployment/ckan-dgp -- \
              python3 -m datacity_ckan_dgp.operators.{{ "{{inputs.parameters.operator}}" }} '{{ "{{inputs.parameters.config_json}}" }}' \
                2>&1 | tee /tmp/log.txt
            echo "Execution completed successfully" 2>&1 | tee /tmp/log.txt
      outputs:
        parameters:
          - name: log
            valueFrom:
              path: /tmp/log.txt
