{{- range $instance, $organizations := .Values.genericFetcherInstanceOrganizationWorkflows }}
 {{- range $organization, $workflows := $organizations }}
   {{- range $workflow := $workflows }}
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: generic-fetcher-{{ $workflow.name_suffix }}
spec:
  entrypoint: dgp-operator-runner.dgp-operator-runner
  workflowTemplateRef:
    name: dgp-operator-runner
  arguments:
    parameters:
      - name: operator
        value: generic_fetcher
      - name: config_json
        value: |
          {
            "source_url": {{ $workflow.source_url | quote }},
            "target_instance_name": {{ $instance | upper | quote }},
            "target_package_id": {{ $workflow.target_package_id | quote }},
            "target_organization_id": {{ $organization | quote }},
            "source_filter": {{ $workflow.source_filter | toJson }}
          }
---
apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: generic-fetcher-{{ $workflow.name_suffix }}
spec:
  schedule: "0 0 1 * *"
  concurrencyPolicy: Forbid
  workflowSpec:
    workflowTemplateRef:
      name: generic-fetcher-{{ $workflow.name_suffix }}
---
   {{- end }}
 {{- end }}
{{- end }}
