{{- range $instance, $organizations := .Values.genericFetcherInstanceOrganizationWorkflows }}
 {{- range $organization, $workflows := $organizations }}
   {{- range $workflow := $workflows }}
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: generic-fetcher-{{ $workflow.name_suffix }}
  labels:
    datacity-workflow: generic-fetcher
    datacity-instance: {{ $instance | quote }}
    datacity-organization: {{ $organization | quote }}
spec:
  entrypoint: generic-fetcher
  synchronization:
    semaphore:
      configMapKeyRef:
        name: argo-workflows
        key: datacity-concurrency
  templates:
    - name: generic-fetcher
      synchronization:
        mutex:
          name: instance-{{ $instance }}
      steps:
        - - name: call-template
            templateRef:
              name: dgp-operator-runner
              template: dgp-operator-runner
            arguments:
              parameters:
                - name: operator
                  value: generic_fetcher
                - name: config_json
                  value: |
                    {
                      "source_url": {{ $workflow.source_url | quote }},
                      "target_instance_name": {{ $instance | upper | quote }},
                      "target_package_id": {{ $workflow.target_package_id | quote }},
                      "target_organization_id": {{ $organization | quote }},
                      "source_filter": {{ $workflow.source_filter | toJson }}
                      {{- if $workflow.post_processing }},"post_processing": {{ $workflow.post_processing | toJson }}{{- end }}
                    }
---
apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: generic-fetcher-{{ $workflow.name_suffix }}
  labels:
    datacity-workflow: generic-fetcher
    datacity-instance: {{ $instance | quote }}
    datacity-organization: {{ $organization | quote }}
spec:
  schedule: {{ $workflow.schedule | quote }}
  concurrencyPolicy: Forbid
  workflowSpec:
    workflowTemplateRef:
      name: generic-fetcher-{{ $workflow.name_suffix }}
---
   {{- end }}
 {{- end }}
{{- end }}
