name: CI
on:
  push:
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - env:
        JENKINS_USER: ${{ secrets.JENKINS_USER }}
        JENKINS_TOKEN: ${{ secrets.JENKINS_TOKEN }}
        JENKINS_UPDATE_INSTANCE_URL: ${{ secrets.JENKINS_UPDATE_INSTANCE_URL }}
      run: |
        if [ "${GITHUB_REF}" == "refs/heads/master" ]; then
          LAST_COMMIT_MSG=$(git log -1 --pretty=format:"%s") &&\
          if echo "${LAST_COMMIT_MSG}" | grep -- --update-instances; then
            GOT_UPDATE_INSTANCES=0
            for WORD in $LAST_COMMIT_MSG; do
              if [ "${GOT_UPDATE_INSTANCES}" == "1" ]; then
                echo updating instance $WORD &&\
                curl --user "${JENKINS_USER}:${JENKINS_TOKEN}" -X POST "${JENKINS_UPDATE_INSTANCE_URL}?INSTANCE_NAME=$WORD"
              elif [ "${WORD}" == "--update-instances" ]; then
                GOT_UPDATE_INSTANCES=1
              fi
            done
          fi
        fi
